export default function Signals() {
  const signals = [
    {
      symbol: "EURUSD",
      direction: "Buy",
      entry: 1.0850,
      stopLoss: 1.0820,
      takeProfit: 1.0920,
      confidence: 85,
    },
    {
      symbol: "GBPUSD",
      direction: "Sell",
      entry: 1.2750,
      stopLoss: 1.2780,
      takeProfit: 1.2680,
      confidence: 78,
    },
    {
      symbol: "USDJPY",
      direction: "Buy",
      entry: 157.50,
      stopLoss: 157.20,
      takeProfit: 158.20,
      confidence: 92,
    },
    {
      symbol: "XAUUSD",
      direction: "Sell",
      entry: 2050.00,
      stopLoss: 2060.00,
      takeProfit: 2020.00,
      confidence: 70,
    },
  ];

  return (
    <div className="page-section">
      <section className="card signals-header">
        <div className="section-header">
          <div>
            <p className="eyebrow">Trading Signals</p>
            <h3>Real-time Trade Opportunities</h3>
          </div>
        </div>
        <p className="signals-description">
          Professional trade signals generated by our AI algorithms. Use at your own risk.
        </p>
      </section>

      <div className="signals-grid">
        {signals.map((signal, idx) => (
          <section key={idx} className="card signal-card">
            <div className="signal-header">
              <h3>{signal.symbol}</h3>
              <span className={`signal-direction ${signal.direction.toLowerCase()}`}>
                {signal.direction}
              </span>
            </div>
            <div className="signal-details">
              <div className="signal-row">
                <span>Entry</span>
                <strong>{signal.entry}</strong>
              </div>
              <div className="signal-row">
                <span>Stop Loss</span>
                <strong className="negative">{signal.stopLoss}</strong>
              </div>
              <div className="signal-row">
                <span>Take Profit</span>
                <strong className="positive">{signal.takeProfit}</strong>
              </div>
              <div className="signal-row">
                <span>Confidence</span>
                <strong>{signal.confidence}%</strong>
              </div>
            </div>
            <button className="primary-button" type="button">
              Execute Trade
            </button>
          </section>
        ))}
      </div>
    </div>
  );
}